export { default as Advantages } from "./Advantages.astro";
export { default as Categories } from "./Categories.astro";
export { default as Gira } from "./Gira.astro";
export { default as Hero } from "./Hero.astro";
export { default as Portfolio } from "./Portfolio.astro";
export { default as Services } from "./Services.astro";
export { default as Stats } from "./Stats.astro";
export { default as Steps } from "./Steps.astro";
export { default as Team } from "./Team.astro";
